// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/asynccnu/ccnubox-be/be-content/conf"
	"github.com/asynccnu/ccnubox-be/be-content/cron"
	"github.com/asynccnu/ccnubox-be/be-content/grpc"
	"github.com/asynccnu/ccnubox-be/be-content/ioc"
	"github.com/asynccnu/ccnubox-be/be-content/repository"
	"github.com/asynccnu/ccnubox-be/be-content/service"
)

// Injectors from wire.go:

func InitApp() *App {
	infraConf := conf.InitInfraConfig()
	db := ioc.InitDB(infraConf)
	cmdable := ioc.InitRedis(infraConf)
	serverConf := conf.InitServerConf()
	logger := ioc.InitLogger(serverConf)
	contentRepo := repository.NewCalendarRepo(db, cmdable, logger)
	calendarService := service.NewCalendarService(contentRepo, logger)
	repositoryContentRepo := repository.NewBannerRepo(db, cmdable, logger)
	bannerService := service.NewBannerService(repositoryContentRepo, logger)
	contentRepo2 := repository.NewDepartmentRepo(db, cmdable, logger)
	departmentService := service.NewDepartmentService(contentRepo2, logger)
	contentRepo3 := repository.NewWebsiteRepo(db, cmdable, logger)
	websiteService := service.NewWebsiteService(contentRepo3, logger)
	contentRepo4 := repository.NewInfoSumRepo(db, cmdable, logger)
	infoSumService := service.NewInfoSumService(contentRepo4, logger)
	contentRepo5 := repository.NewVersionRepo(db, cmdable, logger)
	versionService := service.NewVersionService(contentRepo5, logger)
	contentRepo6 := repository.NewSemesterRepo(db, cmdable, logger)
	semesterService := service.NewSemesterService(contentRepo6, logger)
	contentServiceServer := grpc.NewCalendarServiceServer(calendarService, bannerService, departmentService, websiteService, infoSumService, versionService, semesterService)
	client := ioc.InitEtcdClient(infraConf)
	server := ioc.InitGRPCxKratosServer(contentServiceServer, client, logger, infraConf)
	qiniuClient := ioc.InitQiniu(serverConf)
	calendarController := cron.NewCalendarController(calendarService, qiniuClient, logger, serverConf)
	v := cron.NewCron(calendarController)
	v2 := ioc.InitOTel(serverConf)
	app := NewApp(server, v, v2)
	return app
}
