// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/asynccnu/ccnubox-be/be-classlist/internal/biz"
	"github.com/asynccnu/ccnubox-be/be-classlist/internal/client"
	"github.com/asynccnu/ccnubox-be/be-classlist/internal/conf"
	"github.com/asynccnu/ccnubox-be/be-classlist/internal/data"
	"github.com/asynccnu/ccnubox-be/be-classlist/internal/pkg/crawler"
	"github.com/asynccnu/ccnubox-be/be-classlist/internal/registry"
	"github.com/asynccnu/ccnubox-be/be-classlist/internal/server"
	"github.com/asynccnu/ccnubox-be/be-classlist/internal/service"
	"github.com/go-kratos/kratos/v2"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(string2 string, confServer *conf.Server, confData *conf.Data, confRegistry *conf.Registry, schoolDay *conf.SchoolDay, defaults *conf.Defaults, zapLogConfigs *conf.ZapLogConfigs) (*kratos.App, func(), error) {
	env := client.NewEnv(string2)
	logger := data.NewLogger(zapLogConfigs)
	logLogger := data.NewKratosLogger(logger)
	loggerInterface := data.NewGromLogger(logger)
	db := data.NewDB(confData, logger, loggerInterface)
	dataData, cleanup, err := data.NewData(confData, db, logger)
	if err != nil {
		return nil, nil, err
	}
	classInfoDBRepo := data.NewClassInfoDBRepo(dataData)
	redisClient := data.NewRedisDB(confData, logger)
	classInfoCacheRepo := data.NewClassInfoCacheRepo(redisClient, confServer)
	classInfoRepo := data.NewClassInfoRepo(classInfoDBRepo, classInfoCacheRepo)
	studentAndCourseDBRepo := data.NewStudentAndCourseDBRepo(dataData)
	studentAndCourseCacheRepo := data.NewStudentAndCourseCacheRepo(redisClient, confServer)
	studentAndCourseRepo := data.NewStudentAndCourseRepo(studentAndCourseDBRepo, studentAndCourseCacheRepo)
	classRepo := data.NewClassRepo(classInfoRepo, dataData, studentAndCourseRepo)
	etcdRegistry := registry.NewRegistrarServer(confRegistry, logLogger)
	proxyClient, err := client.InitProxyClient(etcdRegistry, confRegistry, logLogger, env)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	proxyGetter := crawler.NewProxyGetter(proxyClient)
	crawler3 := crawler.NewClassCrawler3(proxyGetter)
	jxbDBRepo := data.NewJxbDBRepo(dataData)
	userSvc, err := client.NewUserSvc(etcdRegistry, confRegistry, env)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	kafkaProducerBuilder := data.NewKafkaProducerBuilder(confData)
	kafkaConsumerBuilder := data.NewKafkaConsumerBuilder(confData)
	delayKafkaConfig := data.NewDelayKafkaConfig()
	delayQueue, cleanup2, err := data.NewDelayKafka(kafkaProducerBuilder, kafkaConsumerBuilder, delayKafkaConfig, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	refreshLogRepo := data.NewRefreshLogRepo(db, confServer)
	cronTaskExecute := biz.NewCronTaskExecute(logger, studentAndCourseDBRepo, crawler3, userSvc, classRepo)
	classUsecase, cleanup3 := biz.NewClassUsecase(classRepo, crawler3, jxbDBRepo, userSvc, delayQueue, refreshLogRepo, confServer, cronTaskExecute)
	classListService := service.NewClasserService(classUsecase, schoolDay, logger, defaults)
	grpcServer := server.NewGRPCServer(confServer, classListService, logLogger)
	app := newApp(env, logLogger, grpcServer, etcdRegistry, confServer)
	return app, func() {
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
